//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otrezki
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public double SegmentStartX1 { get; set; }
        public double SegmentStartY1 { get; set; }
        public double SegmentStartX2 { get; set; }
        public double SegmentStartY2 { get; set; }
        public Nullable<double> SegmentStartX3 { get; set; }
        public Nullable<double> SegmentStartY3 { get; set; }
        public Nullable<double> SegmentStartX4 { get; set; }
        public Nullable<double> SegmentStartY4 { get; set; }
    }
}
